Program.create( { :name => 'Foundation Safety and Rescue Training', :program_type => Pna::ProgramType::SAFETY, :award_attributes => { :name => 'Foundation Safety and Rescue', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Paddlesport Start', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '1 Star Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '1 Star', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '2 Star Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '2 Star', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '3 Star Sea Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '3 Star Sea', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '3 Star Canoe Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '3 Star Canoe', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '3 Star White Water Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '3 Star White Water', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '3 Star Surf Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '3 Star Surf', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '4 Star Sea Training', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '4 Star Sea Assessment', :program_type => Pna::ProgramType::LEADERSHIP, :award_attributes => { :name => '4 Star Sea Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '4 Star Canoe Training', :program_type => Pna::ProgramType::LEADERSHIP } )
Program.create( { :name => '4 Star Canoe Assessment', :program_type => Pna::ProgramType::LEADERSHIP, :award_attributes => { :name => '4 Star Canoe Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '4 Star White Water Training', :program_type => Pna::ProgramType::LEADERSHIP } )
Program.create( { :name => '4 Star White Water Assessment', :program_type => Pna::ProgramType::LEADERSHIP, :award_attributes => { :name => '4 Star White Water Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '4 Star Surf Training', :program_type => Pna::ProgramType::LEADERSHIP } )
Program.create( { :name => '4 Star Surf Assessment', :program_type => Pna::ProgramType::LEADERSHIP, :award_attributes => { :name => '4 Star Surf Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => 'Coastal Navigation', :program_type => Pna::ProgramType::OTHER, :award_attributes => { :name => 'Coastal Navigation and Tidal Planning', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'White Water Safety and Rescue', :program_type => Pna::ProgramType::SAFETY, :award_attributes => { :name => 'White Water Safety and Rescue', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => '5 Star Sea Training', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '5 Star Sea Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '5 Star Sea Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '5 Star Canoe Training', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '5 Star Canoe Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '5 Star Canoe Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '5 Star White Water Training', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '5 Star White Water Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '5 Star White Water Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => '5 Star Surf Training', :program_type => Pna::ProgramType::PERFORMANCE } )
Program.create( { :name => '5 Star Surf Assessment', :program_type => Pna::ProgramType::PERFORMANCE, :award_attributes => { :name => '5 Star Surf Leader', :award_type => Pna::ProgramType::PERFORMANCE } } )
Program.create( { :name => 'Open Water Navigation', :program_type => Pna::ProgramType::OTHER, :award_attributes => { :name => 'Open Water Navigation', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Coach Level 1', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 1 Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Coach Level 2 Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 2 Assessment', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 2 Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Moderate Water Sea Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Moderate Water Sea Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Moderate Water Sea Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Moderate Water Canoe Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Moderate Water Canoe Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Moderate Water Canoe Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Moderate Water White Water Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Moderate Water White Water Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Moderate Water White Water Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Moderate Water Surf Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Moderate Water Surf Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Moderate Water Surf Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Coach Level 3 Generic Core Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 3 Sea Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 3 Sea Assessment', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 3 Sea Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Coach Level 3 Canoe Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 3 Canoe Assessment', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 3 Canoe Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Coach Level 3 White Water Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 3 White Water Assessment', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 3 White Water Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Coach Level 3 Surf Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Coach Level 3 Surf Assessment', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Level 3 Surf Coach', :award_type => Pna::ProgramType::COACHING } } )
Program.create( { :name => 'Advanced Water Sea Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Advanced Water Sea Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Advanced Water Sea Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Advanced Water Canoe Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Advanced Water Canoe Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Advanced Water Canoe Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Advanced Water White Water Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Advanced Water White Water Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Advanced Water White Water Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Advanced Water Surf Training', :program_type => Pna::ProgramType::COACHING } )
Program.create( { :name => 'Advanced Water Surf Endorsement', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Advanced Water Surf Endorsement', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Coaching the Mind', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Coaching the Mind', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Intermediate Coaching the Mind', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Intermediate Coaching the Mind', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Coaching Young Paddlers', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Coaching Young Paddlers', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Fitness for Paddlesports', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Fitness for Paddlesports', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Mentoring Skills for Paddlesport Coaches', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Mentoring Skills for Paddlesport Coaches', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Outdoor Education and Paddlesports', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Outdoor Education and Paddlesports', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Performance Planning Skills for Paddlers', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Performance Planning Skills for Paddlers', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Paddle-Ability: An Introduction to Disability Awareness', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Paddle-Ability: An Introduction to Disability Awareness', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Foundation Fundamental Paddlesport Skills', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Foundation Fundamental Paddlesport Skills', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Intermediate Optimizing Performance 1', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Intermediate Optimizing Performance 1', :award_type => Pna::ProgramType::ENDORSEMENT } } )
Program.create( { :name => 'Intermediate Optimizing Performance 2', :program_type => Pna::ProgramType::COACHING, :award_attributes => { :name => 'Intermediate Optimizing Performance 2', :award_type => Pna::ProgramType::ENDORSEMENT } } )

Award.create( { :name => 'FSRT Provider', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => 'Level 1 Tutor', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => 'Level 1 Director', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => 'Level 2 Tutor', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => 'Level 2 Director', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '4 Star Trainer Sea', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '5 Star Trainer Sea', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '4 Star Trainer Canoe', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '5 Star Trainer Canoe', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '4 Star Trainer White Water', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '5 Star Trainer White Water', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '4 Star Trainer Surf', :award_type => Pna::ProgramType::ENDORSEMENT } )
Award.create( { :name => '5 Star Trainer Surf', :award_type => Pna::ProgramType::ENDORSEMENT } )

