Program.create( { :name => 'Foundation Safety and Rescue Training', :program_type => Program::PROGRAM_TYPES[ :safety ], :award_attributes => { :name => 'Foundation Safety and Rescue' } } )
Program.create( { :name => 'Paddlesport Start', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '1 Star Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '1 Star' } } )
Program.create( { :name => '2 Star Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '2 Star' } } )
Program.create( { :name => '3 Star Sea Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '3 Star Sea' } } )
Program.create( { :name => '3 Star Canoe Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '3 Star Canoe' } } )
Program.create( { :name => '3 Star White Water Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '3 Star White Water' } } )
Program.create( { :name => '3 Star Surf Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '3 Star Surf' } } )
Program.create( { :name => '4 Star Sea Training', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '4 Star Sea Assessment', :program_type => Program::PROGRAM_TYPES[ :leadership ], :award_attributes => { :name => '4 Star Sea Leader' } } )
Program.create( { :name => '4 Star Canoe Training', :program_type => Program::PROGRAM_TYPES[ :leadership ] } )
Program.create( { :name => '4 Star Canoe Assessment', :program_type => Program::PROGRAM_TYPES[ :leadership ], :award_attributes => { :name => '4 Star Canoe Leader' } } )
Program.create( { :name => '4 Star White Water Training', :program_type => Program::PROGRAM_TYPES[ :leadership ] } )
Program.create( { :name => '4 Star White Water Assessment', :program_type => Program::PROGRAM_TYPES[ :leadership ], :award_attributes => { :name => '4 Star White Water Leader' } } )
Program.create( { :name => '4 Star Surf Training', :program_type => Program::PROGRAM_TYPES[ :leadership ] } )
Program.create( { :name => '4 Star Surf Assessment', :program_type => Program::PROGRAM_TYPES[ :leadership ], :award_attributes => { :name => '4 Star Surf Leader' } } )
Program.create( { :name => 'Coastal Navigation', :program_type => Program::PROGRAM_TYPES[ :other ], :award_attributes => { :name => 'Coastal Navigation and Tidal Planning' } } )
Program.create( { :name => 'White Water Safety and Rescue', :program_type => Program::PROGRAM_TYPES[ :safety ], :award_attributes => { :name => 'White Water Safety and Rescue' } } )
Program.create( { :name => '5 Star Sea Training', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '5 Star Sea Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '5 Star Sea Leader' } } )
Program.create( { :name => '5 Star Canoe Training', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '5 Star Canoe Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '5 Star Canoe Leader' } } )
Program.create( { :name => '5 Star White Water Training', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '5 Star White Water Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '5 Star White Water Leader' } } )
Program.create( { :name => '5 Star Surf Training', :program_type => Program::PROGRAM_TYPES[ :performance ] } )
Program.create( { :name => '5 Star Surf Assessment', :program_type => Program::PROGRAM_TYPES[ :performance ], :award_attributes => { :name => '5 Star Surf Leader' } } )
Program.create( { :name => 'Open Water Navigation', :program_type => Program::PROGRAM_TYPES[ :other ], :award_attributes => { :name => 'Open Water Navigation' } } )
Program.create( { :name => 'UKCC Coach Level 1', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 1 Coach' } } )
Program.create( { :name => 'UKCC Coach Level 2 Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 2 Assessment', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 2 Coach' } } )
Program.create( { :name => 'Moderate Water Sea Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Moderate Water Sea Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Moderate Water Sea Endorsement' } } )
Program.create( { :name => 'Moderate Water Canoe Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Moderate Water Canoe Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Moderate Water Canoe Endorsement' } } )
Program.create( { :name => 'Moderate Water White Water Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Moderate Water White Water Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Moderate Water White Water Endorsement' } } )
Program.create( { :name => 'Moderate Water Surf Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Moderate Water Surf Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Moderate Water Surf Endorsement' } } )
Program.create( { :name => 'UKCC Coach Level 3 Generic Core Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 3 Sea Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 3 Sea Assessment', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 3 Sea Coach' } } )
Program.create( { :name => 'UKCC Coach Level 3 Canoe Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 3 Canoe Assessment', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 3 Canoe Coach' } } )
Program.create( { :name => 'UKCC Coach Level 3 White Water Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 3 White Water Assessment', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 3 White Water Coach' } } )
Program.create( { :name => 'UKCC Coach Level 3 Surf Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'UKCC Coach Level 3 Surf Assessment', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'UKCC Level 3 Surf Coach' } } )
Program.create( { :name => 'Advanced Water Sea Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Advanced Water Sea Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Advanced Water Sea Endorsement' } } )
Program.create( { :name => 'Advanced Water Canoe Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Advanced Water Canoe Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Advanced Water Canoe Endorsement' } } )
Program.create( { :name => 'Advanced Water White Water Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Advanced Water White Water Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Advanced Water White Water Endorsement' } } )
Program.create( { :name => 'Advanced Water Surf Training', :program_type => Program::PROGRAM_TYPES[ :coaching ] } )
Program.create( { :name => 'Advanced Water Surf Endorsement', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Advanced Water Surf Endorsement' } } )
Program.create( { :name => 'Foundation Coaching the Mind', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Coaching the Mind' } } )
Program.create( { :name => 'Intermediate Coaching the Mind', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Intermediate Coaching the Mind' } } )
Program.create( { :name => 'Foundation Coaching Young Paddlers', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Coaching Young Paddlers' } } )
Program.create( { :name => 'Foundation Fitness for Paddlesports', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Fitness for Paddlesports' } } )
Program.create( { :name => 'Foundation Mentoring Skills for Paddlesport Coaches', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Mentoring Skills for Paddlesport Coaches' } } )
Program.create( { :name => 'Foundation Outdoor Education and Paddlesports', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Outdoor Education and Paddlesports' } } )
Program.create( { :name => 'Foundation Performance Planning Skills for Paddlers', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Performance Planning Skills for Paddlers' } } )
Program.create( { :name => 'Foundation Paddle-Ability: An Introduction to Disability Awareness', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Paddle-Ability: An Introduction to Disability Awareness' } } )
Program.create( { :name => 'Foundation Fundamental Paddlesport Skills', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Foundation Fundamental Paddlesport Skills' } } )
Program.create( { :name => 'Intermediate Optimizing Performance 1', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Intermediate Optimizing Performance 1' } } )
Program.create( { :name => 'Intermediate Optimizing Performance 2', :program_type => Program::PROGRAM_TYPES[ :coaching ], :award_attributes => { :name => 'Intermediate Optimizing Performance 2' } } )

Award.create( { :name => 'FSRT Provider' } )
Award.create( { :name => 'Level 1 Tutor' } )
Award.create( { :name => 'Level 1 Director' } )
Award.create( { :name => 'Level 2 Tutor' } )
Award.create( { :name => 'Level 2 Director' } )
Award.create( { :name => '4 Star Trainer Sea' } )
Award.create( { :name => '5 Star Trainer Sea' } )
Award.create( { :name => '4 Star Trainer Canoe' } )
Award.create( { :name => '5 Star Trainer Canoe' } )
Award.create( { :name => '4 Star Trainer White Water' } )
Award.create( { :name => '5 Star Trainer White Water' } )
Award.create( { :name => '4 Star Trainer Surf' } )
Award.create( { :name => '5 Star Trainer Surf' } )

