# encoding: utf-8

# Derived from Spree Commerce
# https://github.com/spree/spree
#
# Copyright © 2007-2013, Spree Commerce Inc. and other contributors. All rights
# reserved.
#
# See CONTRIB-LICENCE for Spree License details

country = Country.find_by_name('United States')

State.find_or_create_by_name!({"name"=>"Michigan", "abbr"=>"MI", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"South Dakota", "abbr"=>"SD", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Washington", "abbr"=>"WA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Wisconsin", "abbr"=>"WI", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Arizona", "abbr"=>"AZ", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Illinois", "abbr"=>"IL", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"New Hampshire", "abbr"=>"NH", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"North Carolina", "abbr"=>"NC", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Kansas", "abbr"=>"KS", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Missouri", "abbr"=>"MO", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Arkansas", "abbr"=>"AR", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Nevada", "abbr"=>"NV", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"District of Columbia", "abbr"=>"DC", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Idaho", "abbr"=>"ID", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Nebraska", "abbr"=>"NE", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Pennsylvania", "abbr"=>"PA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Hawaii", "abbr"=>"HI", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Utah", "abbr"=>"UT", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Vermont", "abbr"=>"VT", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Delaware", "abbr"=>"DE", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Rhode Island", "abbr"=>"RI", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Oklahoma", "abbr"=>"OK", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Louisiana", "abbr"=>"LA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Montana", "abbr"=>"MT", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Tennessee", "abbr"=>"TN", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Maryland", "abbr"=>"MD", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Florida", "abbr"=>"FL", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Virginia", "abbr"=>"VA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Minnesota", "abbr"=>"MN", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"New Jersey", "abbr"=>"NJ", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Ohio", "abbr"=>"OH", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"California", "abbr"=>"CA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"North Dakota", "abbr"=>"ND", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Maine", "abbr"=>"ME", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Indiana", "abbr"=>"IN", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Texas", "abbr"=>"TX", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Oregon", "abbr"=>"OR", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Wyoming", "abbr"=>"WY", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Alabama", "abbr"=>"AL", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Iowa", "abbr"=>"IA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Mississippi", "abbr"=>"MS", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Kentucky", "abbr"=>"KY", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"New Mexico", "abbr"=>"NM", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Georgia", "abbr"=>"GA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Colorado", "abbr"=>"CO", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Massachusetts", "abbr"=>"MA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Connecticut", "abbr"=>"CT", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"New York", "abbr"=>"NY", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"South Carolina", "abbr"=>"SC", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Alaska", "abbr"=>"AK", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"West Virginia", "abbr"=>"WV", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"U.S. Armed Forces – Americas", "abbr"=>"AA", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"U.S. Armed Forces – Europe", "abbr"=>"AE", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"U.S. Armed Forces – Pacific", "abbr"=>"AP", :country=>country}, :without_protection => true)

country = Country.find_by_name( 'Canada' )

State.find_or_create_by_name!({"name"=>"Alberta", "abbr"=>"AB", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"British Columbia", "abbr"=>"BC", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Manitoba", "abbr"=>"MB", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"New Brunswick", "abbr"=>"NB", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Newfoundland and Labrador", "abbr"=>"NL", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Nova Scotia", "abbr"=>"NS", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Northwest Territories", "abbr"=>"NT", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Nunavut", "abbr"=>"NU", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Ontario", "abbr"=>"ON", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Prince Edward Island", "abbr"=>"PE", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Quebec", "abbr"=>"QC", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Saskatchewan", "abbr"=>"SK", :country=>country}, :without_protection => true)
State.find_or_create_by_name!({"name"=>"Yukon", "abbr"=>"YT", :country=>country}, :without_protection => true)
